name: tiend_thesis_2022
channels:
  -defaults
dependencies:
  - python=3.9
  - pip
  - conda-build
  - pytest
  - ffmpeg
  - numpy
  - pandas
  - matplotlib
  # medleydb requirements
  - pyyaml = 5.41
  - scikit-learn >= 0.1
  pip:
    - librosa==0.9.2
    - sox >= 1.2.3
